// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Promotion.Models
{
    public partial class PromotionDetail
    {
        public Guid PromotionDetailId { get; set; }
        public string PromotionId { get; set; }
        public string StoreId { get; set; }

        public virtual PromotionHeader Promotion { get; set; }
        public virtual Store Store { get; set; }
    }
}