// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Promotion.Models
{
    public partial class Store
    {
        public Store()
        {
            PromotionDetails = new HashSet<PromotionDetail>();
        }

        public string StoreId { get; set; }
        public string StoreName { get; set; }

        public virtual ICollection<PromotionDetail> PromotionDetails { get; set; }
    }
}